fixtures:
  repositories:
    "puppi":  "git://github.com/example42/puppi.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "concat": "git://github.com/puppetlabs/puppetlabs-concat.git"
  symlinks:
    "ssmtp": "#{source_dir}"

